name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    if: github.ref_type == 'branch' && github.ref_name != 'main'
    uses: ./.github/workflows/test.yml

  code_quality:
    if: github.ref_type == 'branch' && github.ref_name != 'main'
    uses: ./.github/workflows/code_quality.yml

  publish:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/publish.yml
